### ISSUE TITLE
MailTo doesn't work

### ISSUE THREAD

**Issue by leoskingsley** [leoskingsley/xhd#1]
Trying a new method. Should be going soon.

**Comment by Louis-Clelland** [comment]
Did you get an email?

**Comment by Louis-Clelland** [comment]
I think this might be a server side issue

**Comment by Louis-Clelland** [comment]
We need to move from iis express (windows 10) to iis (windows server) Then MailTo should work.

**Comment by Louis-Clelland** [comment]
Fixed. We are no longer using php and smtp, we will be using google forms. So i am deleting send.php and sent.html because they are not needed anymore. Also i have added a link to the form in the help-me.html file.
